name: Continuous Integration
on:
  pull_request:
  push:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Solhint
        run: npm i

      - name: Run Linter
        run: npm run lint

      - name: Build Forge Image
        run: make build

      - name: Run Unit Tests
        run: make test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Integration Tests
        run: make anvil-test

  analyze-message-transmitter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Static Analysis on Message Transmitter
        run: make analyze-message-transmitter

  analyze-token-messenger-minter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Static Analysis on Token Messenger Minter
        run: make analyze-token-messenger-minter

  scan:
    needs: lint-and-test
    if: github.event_name == 'pull_request'
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: lint-and-test
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1
